# Generated by Django 5.1.3 on 2024-11-28 04:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsArticle',
            new_name='News',
        ),
    ]
