# Generated by Django 5.1.3 on 2024-11-28 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_newsarticle_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-pub_date'], 'verbose_name_plural': 'News'},
        ),
    ]
